/// Flutter icons StarWarsFreeIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StarWarsFreeIcons
///      fonts:
///       - asset: fonts/StarWarsFreeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class StarWarsFreeIcons {
  StarWarsFreeIcons._();

  static const _kFontFam = 'StarWarsFreeIcons';
  static const _kFontPkg = null;

  static const IconData star_wars_battle_droid = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_wars_bb8 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_wars_boba_fett = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_wars_c3po = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_wars_darth_vader = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_wars_death_star = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_wars_falcon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_wars_kylo = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_wars_r2d2 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_wars_storm_trooper = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_wars_storm_trooper_2 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_wars_storm_trooper_3 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
